project:
  type: website
  output-dir: docs

website:
  title: "National Workshop Health Data Analytics -2023"
  favicon: /images/nwhda_hex.png
  body-header: |
    Registrations have been extended until 17th Nov, 2023. Hurry!!
  margin-header: |
    ![](/images/nwhda_hex.png){width="65%"}
  navbar:
    logo: /images/nwhda_hex.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

